version: 2

project_name: ok

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/ok
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -w -s -extldflags='-static'

dockers:
  - image_templates:
      - ghcr.io/lstig/{{ .ProjectName }}:{{ .Version }}-amd64
    use: buildx
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description="Simple HTTP that responds 'ok'"
      - --label=org.opencontainers.image.url=https://github.com/lstig/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/lstig/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - image_templates:
      - ghcr.io/lstig/{{ .ProjectName }}:{{ .Version }}-arm64
    use: buildx
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description="Simple HTTP that responds 'ok'"
      - --label=org.opencontainers.image.url=https://github.com/lstig/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/lstig/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: ghcr.io/lstig/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/lstig/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/lstig/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: ghcr.io/lstig/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/lstig/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/lstig/{{ .ProjectName }}:{{ .Version }}-arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
